// <auto-generated />
using DataImport.Storage.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataImport.Storage.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210510190740_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataImport.Core.Domain.VendorPriceItem", b =>
                {
                    b.Property<long>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchFive")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchFour")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchOne")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchSeven")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchSix")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchThree")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BranchTwo")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DeliveryTerm")
                        .HasColumnType("decimal(9,1)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceEight")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceEleven")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceFifteen")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceFive")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceFour")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceFourteen")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceNine")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceOne")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceSeven")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceSeventeen")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceSix")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceSixteen")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceTen")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceThirteen")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceThree")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceTwelve")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("PriceTwo")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ProviderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortNumber")
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("VendorNumber")
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("InternalId");

                    b.ToTable("VendorPriceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
